# plugins/DeltaForceStrike/config.yml

world:
  arena: delta_force_strike

# ========== 队列 / 人数（唯一来源）==========
queue:
  team-size: 1          # 每队人数（3v3 时改 3）
  max-players: 2        # 总人数 = 一般 team-size * 2（注意是 max-players 带 s）
  countdown-seconds: 15
  cancel-if-not-full: true
  auto-balance: true
  lock-during-countdown: true

operator:
  enabled: true
  select-enabled: false
  select-seconds: 45

match:
  half-round: 4
  win-target: 5
  max-rounds: 8
  swap-sides-at-half: true

economy:
  start-money: 800
  victory-bonus: 3200
  defeat-bonus: [1600, 2000, 2400]
  loss-streak-bonus: [2000, 2400, 2800]
  pistol-round-bonus: 2400
  kill-reward: 300
  plant-reward: 300
  defuse-reward: 200
  ct-death-bonus-per-t: 100

round:
  prepare-time: 15
  combat-time: 100

player:
  keep-inventory: false
  drop-equipment: false
  armor-vanish: true

bomb:
  plant-time: 3
  explosion-time: 40
  defuse-time: 10
  defuse-time-with-kit: 5

locations:
  queue-spawn:
    world: delta_force_strike
    x: -62.5
    y: -50.0
    z: -121.5
    yaw: 0
    pitch: 0
  team-t-spawn:
    world: delta_force_strike
    x: 17.5
    y: -54.0
    z: -127.5
    yaw: -90
    pitch: 0
  team-ct-spawn:
    world: delta_force_strike
    x: -126.5
    y: -49.0
    z: -65.5
    yaw: 90
    pitch: 0

debug:
  enabled: true
