name: DeltaForceStrike
version: '${version}'
main: org.starset.deltaforcestrike.DeltaForceStrike
api-version: '26.2'
author: 川崎星夕
description: 友谊之约：反制行动 - 3v3 回合制战术竞技

commands:
  dfs:
    description: DeltaForceStrike 主命令
    usage: /dfs <join|leave|shop|agent|info|reload>
    aliases: [delta, fp]
    permission: deltaforcestrike.use

permissions:
  deltaforcestrike.use:
    default: true
  deltaforcestrike.admin:
    default: op
